[2024-03-26T11:58:23.384+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: liver_disease_pipeline.load_schema manual__2024-03-26T11:58:15.453951+00:00 [queued]>
[2024-03-26T11:58:23.396+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: liver_disease_pipeline.load_schema manual__2024-03-26T11:58:15.453951+00:00 [queued]>
[2024-03-26T11:58:23.397+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-03-26T11:58:23.410+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_schema> on 2024-03-26 11:58:15.453951+00:00
[2024-03-26T11:58:23.416+0000] {standard_task_runner.py:60} INFO - Started process 2353 to run task
[2024-03-26T11:58:23.417+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'liver_disease_pipeline', 'load_schema', 'manual__2024-03-26T11:58:15.453951+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpi1fspdpd']
[2024-03-26T11:58:23.420+0000] {standard_task_runner.py:88} INFO - Job 48: Subtask load_schema
[2024-03-26T11:58:23.459+0000] {task_command.py:423} INFO - Running <TaskInstance: liver_disease_pipeline.load_schema manual__2024-03-26T11:58:15.453951+00:00 [running]> on host bda33bc72d25
[2024-03-26T11:58:23.517+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='admin@localhost.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='liver_disease_pipeline' AIRFLOW_CTX_TASK_ID='load_schema' AIRFLOW_CTX_EXECUTION_DATE='2024-03-26T11:58:15.453951+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-26T11:58:15.453951+00:00'
[2024-03-26T11:58:23.518+0000] {logging_mixin.py:188} INFO - Error loading schema from schema_training.json: [Errno 2] No such file or directory: 'schema_training.json'
[2024-03-26T11:58:23.519+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/trainingValidation.py", line 80, in load_schema
    with open(schema_file, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'schema_training.json'
[2024-03-26T11:58:23.529+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=liver_disease_pipeline, task_id=load_schema, execution_date=20240326T115815, start_date=20240326T115823, end_date=20240326T115823
[2024-03-26T11:58:23.539+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 48 for task load_schema ([Errno 2] No such file or directory: 'schema_training.json'; 2353)
[2024-03-26T11:58:23.551+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-26T11:58:23.565+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
