[2024-03-26T12:40:45.999+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: liver_disease_pipeline.validate_data manual__2024-03-26T12:28:24.455820+00:00 [queued]>
[2024-03-26T12:40:46.012+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: liver_disease_pipeline.validate_data manual__2024-03-26T12:28:24.455820+00:00 [queued]>
[2024-03-26T12:40:46.012+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2024-03-26T12:40:46.025+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): validate_data> on 2024-03-26 12:28:24.455820+00:00
[2024-03-26T12:40:46.031+0000] {standard_task_runner.py:60} INFO - Started process 265 to run task
[2024-03-26T12:40:46.033+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'liver_disease_pipeline', 'validate_data', 'manual__2024-03-26T12:28:24.455820+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpkohpellf']
[2024-03-26T12:40:46.037+0000] {standard_task_runner.py:88} INFO - Job 86: Subtask validate_data
[2024-03-26T12:40:46.101+0000] {task_command.py:423} INFO - Running <TaskInstance: liver_disease_pipeline.validate_data manual__2024-03-26T12:28:24.455820+00:00 [running]> on host 26e863625f16
[2024-03-26T12:40:46.180+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='admin@localhost.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='liver_disease_pipeline' AIRFLOW_CTX_TASK_ID='validate_data' AIRFLOW_CTX_EXECUTION_DATE='2024-03-26T12:28:24.455820+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-26T12:28:24.455820+00:00'
[2024-03-26T12:40:46.193+0000] {logging_mixin.py:188} INFO - Error validating CSV files: [Errno 2] No such file or directory: 'artifacts/nonvalidatedData'
[2024-03-26T12:40:46.194+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/trainingValidation.py", line 89, in validate_data
    files = os.listdir(local_folder)
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts/nonvalidatedData'
[2024-03-26T12:40:46.205+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=liver_disease_pipeline, task_id=validate_data, execution_date=20240326T122824, start_date=20240326T124046, end_date=20240326T124046
[2024-03-26T12:40:46.216+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 86 for task validate_data ([Errno 2] No such file or directory: 'artifacts/nonvalidatedData'; 265)
[2024-03-26T12:40:46.248+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-26T12:40:46.271+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
