[2024-04-08T16:23:42.192+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: liver_disease_pipeline_2.model_training manual__2024-04-08T16:23:01.900148+00:00 [queued]>
[2024-04-08T16:23:42.200+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: liver_disease_pipeline_2.model_training manual__2024-04-08T16:23:01.900148+00:00 [queued]>
[2024-04-08T16:23:42.200+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-04-08T16:23:42.214+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): model_training> on 2024-04-08 16:23:01.900148+00:00
[2024-04-08T16:23:42.220+0000] {standard_task_runner.py:60} INFO - Started process 716 to run task
[2024-04-08T16:23:42.222+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'liver_disease_pipeline_2', 'model_training', 'manual__2024-04-08T16:23:01.900148+00:00', '--job-id', '218', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpuo2v6ycc']
[2024-04-08T16:23:42.224+0000] {standard_task_runner.py:88} INFO - Job 218: Subtask model_training
[2024-04-08T16:23:42.261+0000] {task_command.py:423} INFO - Running <TaskInstance: liver_disease_pipeline_2.model_training manual__2024-04-08T16:23:01.900148+00:00 [running]> on host 60be0e44a1a9
[2024-04-08T16:23:42.328+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='admin@localhost.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='liver_disease_pipeline_2' AIRFLOW_CTX_TASK_ID='model_training' AIRFLOW_CTX_EXECUTION_DATE='2024-04-08T16:23:01.900148+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-08T16:23:01.900148+00:00'
[2024-04-08T16:23:42.949+0000] {logging_mixin.py:188} WARNING - 2024/04/08 16:23:42 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logged at level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2024-04-08T16:23:44.193+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/joblib/parallel.py:1332 UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
[2024-04-08T16:23:45.456+0000] {logging_mixin.py:188} INFO - Error in model training: Expected sequence or array-like, got <class 'NoneType'>
[2024-04-08T16:23:45.457+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-04-08T16:23:46.504+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=liver_disease_pipeline_2, task_id=model_training, execution_date=20240408T162301, start_date=20240408T162342, end_date=20240408T162346
[2024-04-08T16:23:46.764+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-08T16:23:46.784+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
