[2024-04-07T17:14:20.315+0000] {processor.py:161} INFO - Started process (PID=179) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:14:20.317+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:14:20.318+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:14:20.318+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:14:23.573+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:14:23.568+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:14:23.576+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:14:23.590+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 3.277 seconds
[2024-04-07T17:14:53.799+0000] {processor.py:161} INFO - Started process (PID=245) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:14:53.800+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:14:53.800+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:14:53.800+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:14:55.699+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:14:55.695+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:14:55.700+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:14:55.715+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.918 seconds
[2024-04-07T17:15:25.921+0000] {processor.py:161} INFO - Started process (PID=293) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:15:25.922+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:15:25.923+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:15:25.923+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:15:27.852+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:15:27.848+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:15:27.854+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:15:27.868+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.949 seconds
[2024-04-07T17:15:58.076+0000] {processor.py:161} INFO - Started process (PID=341) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:15:58.077+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:15:58.078+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:15:58.078+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:16:00.034+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:16:00.030+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:16:00.036+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:16:00.049+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.975 seconds
[2024-04-07T17:17:25.145+0000] {processor.py:161} INFO - Started process (PID=179) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:17:25.147+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:17:25.148+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:17:25.148+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:17:27.425+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:17:27.421+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:17:27.427+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:17:27.441+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 2.299 seconds
[2024-04-07T17:17:57.613+0000] {processor.py:161} INFO - Started process (PID=283) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:17:57.614+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:17:57.615+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:17:57.615+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:17:59.611+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:17:59.607+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:17:59.613+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:17:59.625+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 2.014 seconds
[2024-04-07T17:18:29.854+0000] {processor.py:161} INFO - Started process (PID=612) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:18:29.855+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:18:29.856+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:18:29.856+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:18:31.831+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:18:31.826+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:18:31.833+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:18:31.847+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.996 seconds
[2024-04-07T17:19:02.068+0000] {processor.py:161} INFO - Started process (PID=660) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:19:02.069+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:19:02.070+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:19:02.070+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:19:03.999+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:19:03.995+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:19:04.001+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:19:04.014+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.948 seconds
[2024-04-07T17:19:34.213+0000] {processor.py:161} INFO - Started process (PID=708) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:19:34.214+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:19:34.215+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:19:34.215+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:19:36.126+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:19:36.122+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:19:36.128+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:19:36.141+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.930 seconds
[2024-04-07T17:20:06.333+0000] {processor.py:161} INFO - Started process (PID=756) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:20:06.334+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:20:06.335+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:20:06.334+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:20:08.317+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:20:08.311+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:20:08.319+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:20:08.333+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 2.003 seconds
[2024-04-07T17:20:38.559+0000] {processor.py:161} INFO - Started process (PID=804) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:20:38.560+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:20:38.561+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:20:38.561+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:20:40.437+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:20:40.432+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:20:40.438+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:20:40.453+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.896 seconds
[2024-04-07T17:21:10.695+0000] {processor.py:161} INFO - Started process (PID=852) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:21:10.697+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:21:10.699+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:21:10.698+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:21:12.740+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:21:12.736+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:21:12.742+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:21:12.756+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 2.065 seconds
[2024-04-07T17:21:42.969+0000] {processor.py:161} INFO - Started process (PID=900) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:21:42.970+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:21:42.971+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:21:42.971+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:21:44.911+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:21:44.906+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:21:44.913+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:21:44.925+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.959 seconds
[2024-04-07T17:22:15.183+0000] {processor.py:161} INFO - Started process (PID=948) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:22:15.184+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:22:15.185+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:22:15.184+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:22:17.094+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:22:17.090+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:22:17.096+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:22:17.153+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.973 seconds
[2024-04-07T17:22:47.648+0000] {processor.py:161} INFO - Started process (PID=1003) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:22:47.649+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:22:47.650+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:22:47.650+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:22:49.592+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:22:49.587+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:22:49.594+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:22:49.607+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.961 seconds
[2024-04-07T17:23:19.754+0000] {processor.py:161} INFO - Started process (PID=1051) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:23:19.756+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:23:19.757+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:23:19.756+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:23:21.635+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:23:21.630+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:23:21.636+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:23:21.649+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.897 seconds
[2024-04-07T17:23:51.812+0000] {processor.py:161} INFO - Started process (PID=1099) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:23:51.813+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:23:51.814+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:23:51.813+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:23:53.798+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:23:53.794+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:23:53.800+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:23:53.813+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 2.004 seconds
[2024-04-07T17:24:23.982+0000] {processor.py:161} INFO - Started process (PID=1147) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:24:23.983+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:24:23.984+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:24:23.984+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:24:25.925+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:24:25.921+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:24:25.927+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:24:25.941+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.961 seconds
[2024-04-07T17:24:56.156+0000] {processor.py:161} INFO - Started process (PID=1195) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:24:56.157+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:24:56.159+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:24:56.158+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:24:58.003+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:24:57.999+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:24:58.005+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:24:58.017+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.864 seconds
[2024-04-07T17:25:28.256+0000] {processor.py:161} INFO - Started process (PID=1243) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:25:28.256+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:25:28.257+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:25:28.257+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:25:30.107+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:25:30.103+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:25:30.108+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:25:30.126+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.872 seconds
[2024-04-07T17:26:00.303+0000] {processor.py:161} INFO - Started process (PID=1291) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:26:00.304+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:26:00.305+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:26:00.305+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:26:02.203+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:26:02.199+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:26:02.205+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:26:02.218+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.917 seconds
[2024-04-07T17:26:32.425+0000] {processor.py:161} INFO - Started process (PID=1339) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:26:32.426+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:26:32.427+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:26:32.427+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:26:34.305+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:26:34.301+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:26:34.307+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:26:34.321+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.898 seconds
[2024-04-07T17:27:04.479+0000] {processor.py:161} INFO - Started process (PID=1387) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:27:04.480+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:27:04.481+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:27:04.481+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:27:06.378+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:27:06.374+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:27:06.380+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:27:06.392+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.915 seconds
[2024-04-07T17:27:36.878+0000] {processor.py:161} INFO - Started process (PID=1435) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:27:36.878+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:27:36.879+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:27:36.879+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:27:38.726+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:27:38.720+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:27:38.728+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:27:38.742+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.867 seconds
[2024-04-07T17:28:08.900+0000] {processor.py:161} INFO - Started process (PID=1483) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:28:08.901+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:28:08.901+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:28:08.901+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:28:10.788+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:28:10.784+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:28:10.789+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:28:10.802+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.904 seconds
[2024-04-07T17:28:40.975+0000] {processor.py:161} INFO - Started process (PID=1531) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:28:40.976+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:28:40.977+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:28:40.976+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:28:42.923+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:28:42.918+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:28:42.925+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:28:42.938+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.966 seconds
[2024-04-07T17:29:13.158+0000] {processor.py:161} INFO - Started process (PID=1579) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:29:13.159+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:29:13.159+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:29:13.159+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:29:15.060+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:29:15.056+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:29:15.061+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:29:15.074+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.919 seconds
[2024-04-07T17:29:45.290+0000] {processor.py:161} INFO - Started process (PID=1627) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:29:45.291+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:29:45.292+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:29:45.291+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:29:47.209+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:29:47.204+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:29:47.210+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:29:47.228+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.941 seconds
[2024-04-07T17:31:17.478+0000] {processor.py:161} INFO - Started process (PID=179) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:31:17.480+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:31:17.482+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:31:17.482+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:31:19.819+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:31:19.815+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:31:19.821+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:31:19.835+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 2.359 seconds
[2024-04-07T17:31:50.091+0000] {processor.py:161} INFO - Started process (PID=363) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:31:50.092+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:31:50.093+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:31:50.092+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:31:52.280+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:31:52.275+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:31:52.282+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:31:52.296+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 2.208 seconds
[2024-04-07T17:32:22.515+0000] {processor.py:161} INFO - Started process (PID=611) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:32:22.516+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:32:22.517+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:32:22.517+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:32:24.396+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:32:24.391+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:32:24.398+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:32:24.412+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.899 seconds
[2024-04-07T17:32:54.461+0000] {processor.py:161} INFO - Started process (PID=659) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:32:54.462+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:32:54.463+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:32:54.463+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:32:56.365+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:32:56.361+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:32:56.367+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:32:56.379+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.920 seconds
[2024-04-07T17:33:26.540+0000] {processor.py:161} INFO - Started process (PID=707) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:33:26.541+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:33:26.542+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:33:26.542+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:33:28.571+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:33:28.567+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:33:28.573+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:33:28.585+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 2.048 seconds
[2024-04-07T17:33:58.684+0000] {processor.py:161} INFO - Started process (PID=755) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:33:58.685+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:33:58.686+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:33:58.686+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:34:00.584+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:34:00.579+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:34:00.585+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:34:00.597+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.915 seconds
[2024-04-07T17:34:30.767+0000] {processor.py:161} INFO - Started process (PID=803) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:34:30.768+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:34:30.769+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:34:30.768+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:34:32.614+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:34:32.610+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:34:32.616+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:34:32.629+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.865 seconds
[2024-04-07T17:35:02.772+0000] {processor.py:161} INFO - Started process (PID=851) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:35:02.773+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:35:02.774+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:35:02.774+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:35:04.672+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:35:04.668+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:35:04.674+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:35:04.686+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.916 seconds
[2024-04-07T17:35:34.857+0000] {processor.py:161} INFO - Started process (PID=905) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:35:34.858+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:35:34.859+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:35:34.859+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:35:36.750+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:35:36.746+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:35:36.752+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:35:36.767+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.913 seconds
[2024-04-07T17:36:06.957+0000] {processor.py:161} INFO - Started process (PID=953) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:36:06.958+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:36:06.958+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:36:06.958+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:36:08.856+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:36:08.852+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:36:08.858+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:36:08.871+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.916 seconds
[2024-04-07T17:36:39.050+0000] {processor.py:161} INFO - Started process (PID=1001) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:36:39.051+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:36:39.052+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:36:39.052+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:36:40.952+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:36:40.947+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:36:40.953+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:36:40.966+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.919 seconds
[2024-04-07T17:37:11.066+0000] {processor.py:161} INFO - Started process (PID=1049) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:37:11.067+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:37:11.068+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:37:11.068+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:37:12.990+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:37:12.986+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:37:12.993+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:37:13.006+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.942 seconds
[2024-04-07T17:37:43.188+0000] {processor.py:161} INFO - Started process (PID=1097) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:37:43.189+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:37:43.190+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:37:43.189+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:37:45.153+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:37:45.149+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:37:45.155+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:37:45.169+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.984 seconds
[2024-04-07T17:38:15.414+0000] {processor.py:161} INFO - Started process (PID=1146) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:38:15.415+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:38:15.416+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:38:15.416+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:38:17.336+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:38:17.332+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:38:17.338+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:38:17.352+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.940 seconds
[2024-04-07T17:38:47.596+0000] {processor.py:161} INFO - Started process (PID=1194) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:38:47.597+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:38:47.598+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:38:47.597+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:38:49.488+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:38:49.480+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:38:49.490+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:38:49.503+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.910 seconds
[2024-04-07T17:39:19.693+0000] {processor.py:161} INFO - Started process (PID=1242) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:39:19.694+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:39:19.695+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:39:19.695+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:39:21.656+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:39:21.651+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:39:21.657+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:39:21.671+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.981 seconds
[2024-04-07T17:39:51.858+0000] {processor.py:161} INFO - Started process (PID=1290) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:39:51.859+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:39:51.860+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:39:51.859+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:39:53.748+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:39:53.744+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:39:53.750+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:39:53.762+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.907 seconds
[2024-04-07T17:40:23.959+0000] {processor.py:161} INFO - Started process (PID=1338) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:40:23.960+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:40:23.961+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:40:23.961+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:40:25.899+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:40:25.895+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:40:25.901+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:40:25.915+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.958 seconds
[2024-04-07T17:40:56.103+0000] {processor.py:161} INFO - Started process (PID=1386) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:40:56.104+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:40:56.105+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:40:56.104+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:40:58.061+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:40:58.056+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:40:58.063+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:40:58.076+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.976 seconds
[2024-04-07T17:41:28.527+0000] {processor.py:161} INFO - Started process (PID=1434) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:41:28.528+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:41:28.529+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:41:28.529+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:41:30.432+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:41:30.427+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:41:30.434+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:41:30.448+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.923 seconds
[2024-04-07T17:42:00.672+0000] {processor.py:161} INFO - Started process (PID=1482) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:42:00.673+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:42:00.674+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:42:00.674+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:42:02.545+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:42:02.540+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:42:02.547+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:42:02.559+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.890 seconds
[2024-04-07T17:42:32.729+0000] {processor.py:161} INFO - Started process (PID=1530) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:42:32.730+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:42:32.731+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:42:32.731+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:42:34.673+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:42:34.665+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:42:34.675+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:42:34.687+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.961 seconds
[2024-04-07T17:43:04.879+0000] {processor.py:161} INFO - Started process (PID=1578) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:43:04.880+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:43:04.881+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:43:04.881+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:43:06.905+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:43:06.899+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:43:06.907+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:43:06.921+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 2.044 seconds
[2024-04-07T17:43:37.050+0000] {processor.py:161} INFO - Started process (PID=1632) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:43:37.051+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:43:37.052+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:43:37.052+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:43:38.954+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:43:38.950+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:43:38.956+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:43:38.968+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.921 seconds
[2024-04-07T17:44:09.207+0000] {processor.py:161} INFO - Started process (PID=1680) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:44:09.208+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:44:09.209+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:44:09.209+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:44:11.117+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:44:11.112+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:44:11.119+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:44:11.131+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.927 seconds
[2024-04-07T17:44:41.369+0000] {processor.py:161} INFO - Started process (PID=1728) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:44:41.370+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:44:41.370+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:44:41.370+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:44:43.255+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:44:43.251+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:44:43.257+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:44:43.269+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.903 seconds
[2024-04-07T17:45:13.463+0000] {processor.py:161} INFO - Started process (PID=1776) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:45:13.464+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:45:13.465+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:45:13.465+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:45:15.405+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:45:15.400+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:45:15.407+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:45:15.420+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.959 seconds
[2024-04-07T17:45:45.610+0000] {processor.py:161} INFO - Started process (PID=1824) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:45:45.611+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:45:45.613+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:45:45.612+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:45:47.508+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:45:47.503+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:45:47.509+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:45:47.521+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.913 seconds
[2024-04-07T17:49:17.163+0000] {processor.py:161} INFO - Started process (PID=180) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:49:17.164+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:49:17.165+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:49:17.165+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:49:19.524+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:49:19.520+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:49:19.526+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:49:19.538+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 2.377 seconds
[2024-04-07T17:49:49.700+0000] {processor.py:161} INFO - Started process (PID=246) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:49:49.701+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:49:49.702+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:49:49.702+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:49:51.609+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:49:51.604+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:49:51.610+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:49:51.623+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.925 seconds
[2024-04-07T17:50:21.780+0000] {processor.py:161} INFO - Started process (PID=294) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:50:21.781+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:50:21.782+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:50:21.782+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:50:23.632+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:50:23.628+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:50:23.633+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:50:23.648+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.870 seconds
[2024-04-07T17:50:53.803+0000] {processor.py:161} INFO - Started process (PID=443) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:50:53.804+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:50:53.805+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:50:53.805+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:50:55.769+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:50:55.765+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:50:55.770+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:50:55.783+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.982 seconds
[2024-04-07T17:51:26.004+0000] {processor.py:161} INFO - Started process (PID=550) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:51:26.005+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:51:26.007+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:51:26.006+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:51:28.104+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:51:28.100+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:51:28.106+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:51:28.121+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 2.119 seconds
[2024-04-07T17:51:58.184+0000] {processor.py:161} INFO - Started process (PID=598) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:51:58.185+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:51:58.186+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:51:58.185+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:52:00.095+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:52:00.091+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:52:00.097+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:52:00.110+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.928 seconds
[2024-04-07T17:52:30.321+0000] {processor.py:161} INFO - Started process (PID=646) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:52:30.322+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:52:30.323+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:52:30.323+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:52:32.237+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:52:32.233+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:52:32.239+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:52:32.252+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.933 seconds
[2024-04-07T17:53:02.495+0000] {processor.py:161} INFO - Started process (PID=854) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:53:02.496+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:53:02.497+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:53:02.497+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:53:04.375+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:53:04.370+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:53:04.376+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:53:04.388+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.896 seconds
[2024-04-07T17:53:34.595+0000] {processor.py:161} INFO - Started process (PID=902) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:53:34.596+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:53:34.597+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:53:34.597+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:53:36.543+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:53:36.535+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:53:36.544+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:53:36.557+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.964 seconds
[2024-04-07T17:54:06.745+0000] {processor.py:161} INFO - Started process (PID=950) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:54:06.746+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:54:06.747+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:54:06.746+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:54:08.691+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:54:08.686+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:54:08.692+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:54:08.705+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.962 seconds
[2024-04-07T17:54:38.926+0000] {processor.py:161} INFO - Started process (PID=1005) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:54:38.927+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:54:38.928+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:54:38.928+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:54:40.785+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:54:40.781+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:54:40.787+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:54:40.801+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.877 seconds
[2024-04-07T17:55:11.033+0000] {processor.py:161} INFO - Started process (PID=1053) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:55:11.034+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:55:11.035+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:55:11.035+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:55:13.159+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:55:13.155+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:55:13.161+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:55:13.175+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 2.144 seconds
[2024-04-07T17:55:43.380+0000] {processor.py:161} INFO - Started process (PID=1102) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:55:43.381+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:55:43.382+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:55:43.382+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:55:45.309+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:55:45.304+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:55:45.311+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:55:45.324+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.946 seconds
[2024-04-07T17:56:15.531+0000] {processor.py:161} INFO - Started process (PID=1150) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:56:15.532+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:56:15.533+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:56:15.532+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:56:17.470+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:56:17.465+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:56:17.472+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:56:17.484+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.956 seconds
[2024-04-07T17:56:47.538+0000] {processor.py:161} INFO - Started process (PID=1198) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:56:47.539+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:56:47.540+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:56:47.539+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:56:49.441+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:56:49.436+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:56:49.442+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:56:49.455+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.919 seconds
[2024-04-07T17:57:19.646+0000] {processor.py:161} INFO - Started process (PID=1246) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:57:19.647+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:57:19.648+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:57:19.648+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:57:21.527+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:57:21.523+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:57:21.529+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:57:21.543+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.899 seconds
[2024-04-07T17:57:51.732+0000] {processor.py:161} INFO - Started process (PID=1294) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:57:51.733+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:57:51.734+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:57:51.734+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:57:53.569+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:57:53.564+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:57:53.570+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:57:53.582+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.852 seconds
[2024-04-07T17:58:23.817+0000] {processor.py:161} INFO - Started process (PID=1342) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:58:23.818+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:58:23.819+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:58:23.819+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:58:25.736+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:58:25.732+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:58:25.738+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:58:25.750+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.936 seconds
[2024-04-07T17:58:55.910+0000] {processor.py:161} INFO - Started process (PID=1390) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:58:55.911+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:58:55.912+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:58:55.912+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:58:57.802+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:58:57.798+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:58:57.804+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:58:57.817+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.909 seconds
[2024-04-07T17:59:28.241+0000] {processor.py:161} INFO - Started process (PID=1438) to work on /opt/airflow/dags/evidently.py
[2024-04-07T17:59:28.242+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T17:59:28.243+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:59:28.242+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T17:59:30.129+0000] {logging_mixin.py:188} INFO - [2024-04-07T17:59:30.125+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T17:59:30.130+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T17:59:30.144+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.905 seconds
[2024-04-07T18:00:00.388+0000] {processor.py:161} INFO - Started process (PID=1486) to work on /opt/airflow/dags/evidently.py
[2024-04-07T18:00:00.389+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T18:00:00.390+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:00:00.390+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T18:00:02.226+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:00:02.222+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T18:00:02.227+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T18:00:02.240+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.856 seconds
[2024-04-07T18:00:32.398+0000] {processor.py:161} INFO - Started process (PID=1534) to work on /opt/airflow/dags/evidently.py
[2024-04-07T18:00:32.399+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T18:00:32.399+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:00:32.399+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T18:00:34.240+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:00:34.236+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T18:00:34.241+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T18:00:34.254+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.859 seconds
[2024-04-07T18:01:04.430+0000] {processor.py:161} INFO - Started process (PID=1582) to work on /opt/airflow/dags/evidently.py
[2024-04-07T18:01:04.431+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T18:01:04.432+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:01:04.432+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T18:01:06.338+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:01:06.333+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T18:01:06.339+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T18:01:06.354+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.927 seconds
[2024-04-07T18:01:36.514+0000] {processor.py:161} INFO - Started process (PID=1630) to work on /opt/airflow/dags/evidently.py
[2024-04-07T18:01:36.515+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T18:01:36.516+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:01:36.516+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T18:01:38.403+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:01:38.399+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T18:01:38.404+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T18:01:38.419+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.907 seconds
[2024-04-07T18:02:08.569+0000] {processor.py:161} INFO - Started process (PID=1678) to work on /opt/airflow/dags/evidently.py
[2024-04-07T18:02:08.570+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T18:02:08.571+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:02:08.571+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T18:02:10.431+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:02:10.427+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T18:02:10.432+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T18:02:10.445+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.878 seconds
[2024-04-07T18:02:40.610+0000] {processor.py:161} INFO - Started process (PID=1732) to work on /opt/airflow/dags/evidently.py
[2024-04-07T18:02:40.611+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T18:02:40.612+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:02:40.612+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T18:02:42.427+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:02:42.423+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T18:02:42.429+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T18:02:42.441+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.833 seconds
[2024-04-07T18:03:12.625+0000] {processor.py:161} INFO - Started process (PID=1780) to work on /opt/airflow/dags/evidently.py
[2024-04-07T18:03:12.626+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T18:03:12.627+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:03:12.627+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T18:03:14.470+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:03:14.466+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T18:03:14.472+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T18:03:14.484+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.861 seconds
[2024-04-07T18:03:44.654+0000] {processor.py:161} INFO - Started process (PID=1828) to work on /opt/airflow/dags/evidently.py
[2024-04-07T18:03:44.655+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T18:03:44.656+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:03:44.655+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T18:03:46.497+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:03:46.493+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T18:03:46.498+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T18:03:46.511+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.860 seconds
[2024-04-07T18:04:16.648+0000] {processor.py:161} INFO - Started process (PID=1876) to work on /opt/airflow/dags/evidently.py
[2024-04-07T18:04:16.649+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T18:04:16.650+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:04:16.650+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T18:04:18.572+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:04:18.568+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T18:04:18.574+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T18:04:18.588+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.942 seconds
[2024-04-07T18:04:48.717+0000] {processor.py:161} INFO - Started process (PID=1924) to work on /opt/airflow/dags/evidently.py
[2024-04-07T18:04:48.718+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T18:04:48.719+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:04:48.719+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T18:04:50.586+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:04:50.581+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T18:04:50.588+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T18:04:50.602+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.887 seconds
[2024-04-07T18:05:20.737+0000] {processor.py:161} INFO - Started process (PID=1972) to work on /opt/airflow/dags/evidently.py
[2024-04-07T18:05:20.738+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T18:05:20.739+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:05:20.738+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T18:05:22.676+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:05:22.672+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T18:05:22.678+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T18:05:22.690+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.956 seconds
[2024-04-07T18:05:52.916+0000] {processor.py:161} INFO - Started process (PID=2023) to work on /opt/airflow/dags/evidently.py
[2024-04-07T18:05:52.917+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T18:05:52.918+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:05:52.918+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T18:05:54.947+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:05:54.942+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T18:05:54.949+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T18:05:54.962+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 2.050 seconds
[2024-04-07T18:06:25.122+0000] {processor.py:161} INFO - Started process (PID=2089) to work on /opt/airflow/dags/evidently.py
[2024-04-07T18:06:25.123+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T18:06:25.124+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:06:25.124+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T18:06:26.997+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:06:26.992+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T18:06:27.001+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T18:06:27.017+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.897 seconds
[2024-04-07T18:06:57.212+0000] {processor.py:161} INFO - Started process (PID=2137) to work on /opt/airflow/dags/evidently.py
[2024-04-07T18:06:57.213+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T18:06:57.214+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:06:57.214+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T18:06:59.066+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:06:59.061+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T18:06:59.067+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T18:06:59.080+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.870 seconds
[2024-04-07T18:07:29.266+0000] {processor.py:161} INFO - Started process (PID=2185) to work on /opt/airflow/dags/evidently.py
[2024-04-07T18:07:29.267+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T18:07:29.268+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:07:29.268+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T18:07:31.130+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:07:31.126+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T18:07:31.132+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T18:07:31.144+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.880 seconds
[2024-04-07T18:08:01.288+0000] {processor.py:161} INFO - Started process (PID=2233) to work on /opt/airflow/dags/evidently.py
[2024-04-07T18:08:01.289+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T18:08:01.290+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:08:01.290+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T18:08:03.126+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:08:03.122+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T18:08:03.128+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T18:08:03.143+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.857 seconds
[2024-04-07T18:08:33.365+0000] {processor.py:161} INFO - Started process (PID=2281) to work on /opt/airflow/dags/evidently.py
[2024-04-07T18:08:33.366+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T18:08:33.367+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:08:33.367+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T18:08:35.269+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:08:35.264+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T18:08:35.270+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T18:08:35.283+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.921 seconds
[2024-04-07T18:09:05.504+0000] {processor.py:161} INFO - Started process (PID=2329) to work on /opt/airflow/dags/evidently.py
[2024-04-07T18:09:05.505+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T18:09:05.505+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:09:05.505+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T18:09:07.393+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:09:07.389+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T18:09:07.394+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T18:09:07.406+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.905 seconds
[2024-04-07T18:09:37.823+0000] {processor.py:161} INFO - Started process (PID=2377) to work on /opt/airflow/dags/evidently.py
[2024-04-07T18:09:37.824+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T18:09:37.825+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:09:37.825+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T18:09:39.664+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:09:39.660+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T18:09:39.666+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T18:09:39.678+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.857 seconds
[2024-04-07T18:10:09.871+0000] {processor.py:161} INFO - Started process (PID=2425) to work on /opt/airflow/dags/evidently.py
[2024-04-07T18:10:09.872+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T18:10:09.873+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:10:09.872+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T18:10:11.759+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:10:11.755+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T18:10:11.761+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T18:10:11.773+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.904 seconds
[2024-04-07T18:10:41.935+0000] {processor.py:161} INFO - Started process (PID=2479) to work on /opt/airflow/dags/evidently.py
[2024-04-07T18:10:41.936+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T18:10:41.937+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:10:41.937+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T18:10:43.893+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:10:43.888+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T18:10:43.894+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T18:10:43.907+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.974 seconds
[2024-04-07T18:11:14.040+0000] {processor.py:161} INFO - Started process (PID=2527) to work on /opt/airflow/dags/evidently.py
[2024-04-07T18:11:14.041+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T18:11:14.042+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:11:14.041+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T18:11:15.928+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:11:15.923+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T18:11:15.929+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T18:11:15.941+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.904 seconds
[2024-04-07T18:11:46.099+0000] {processor.py:161} INFO - Started process (PID=2575) to work on /opt/airflow/dags/evidently.py
[2024-04-07T18:11:46.100+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T18:11:46.101+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:11:46.100+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T18:11:48.010+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:11:48.005+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T18:11:48.012+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T18:11:48.025+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.928 seconds
[2024-04-07T18:12:18.106+0000] {processor.py:161} INFO - Started process (PID=2623) to work on /opt/airflow/dags/evidently.py
[2024-04-07T18:12:18.107+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T18:12:18.107+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:12:18.107+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T18:12:20.009+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:12:20.006+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T18:12:20.011+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T18:12:20.024+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.921 seconds
[2024-04-07T18:12:50.188+0000] {processor.py:161} INFO - Started process (PID=2671) to work on /opt/airflow/dags/evidently.py
[2024-04-07T18:12:50.189+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T18:12:50.189+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:12:50.189+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T18:12:52.065+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:12:52.061+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T18:12:52.067+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T18:12:52.079+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.894 seconds
[2024-04-07T18:13:22.245+0000] {processor.py:161} INFO - Started process (PID=2719) to work on /opt/airflow/dags/evidently.py
[2024-04-07T18:13:22.246+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T18:13:22.247+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:13:22.247+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T18:13:24.194+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:13:24.189+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T18:13:24.197+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T18:13:24.211+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.969 seconds
[2024-04-07T18:13:54.404+0000] {processor.py:161} INFO - Started process (PID=2767) to work on /opt/airflow/dags/evidently.py
[2024-04-07T18:13:54.405+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T18:13:54.406+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:13:54.405+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T18:13:56.311+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:13:56.307+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T18:13:56.313+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T18:13:56.326+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.924 seconds
[2024-04-07T18:14:26.531+0000] {processor.py:161} INFO - Started process (PID=2815) to work on /opt/airflow/dags/evidently.py
[2024-04-07T18:14:26.532+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T18:14:26.533+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:14:26.532+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T18:14:28.411+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:14:28.406+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T18:14:28.413+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T18:14:28.426+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.898 seconds
[2024-04-07T18:14:58.653+0000] {processor.py:161} INFO - Started process (PID=2863) to work on /opt/airflow/dags/evidently.py
[2024-04-07T18:14:58.654+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T18:14:58.655+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:14:58.654+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T18:15:00.629+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:15:00.622+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T18:15:00.638+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T18:15:00.658+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 2.007 seconds
[2024-04-07T18:15:30.826+0000] {processor.py:161} INFO - Started process (PID=2911) to work on /opt/airflow/dags/evidently.py
[2024-04-07T18:15:30.827+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T18:15:30.828+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:15:30.828+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T18:15:32.733+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:15:32.729+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T18:15:32.735+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T18:15:32.751+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.927 seconds
[2024-04-07T18:16:02.949+0000] {processor.py:161} INFO - Started process (PID=2959) to work on /opt/airflow/dags/evidently.py
[2024-04-07T18:16:02.950+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T18:16:02.951+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:16:02.951+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T18:16:04.783+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:16:04.779+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T18:16:04.784+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T18:16:04.797+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.850 seconds
[2024-04-07T18:16:35.032+0000] {processor.py:161} INFO - Started process (PID=3007) to work on /opt/airflow/dags/evidently.py
[2024-04-07T18:16:35.033+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T18:16:35.034+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:16:35.034+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T18:16:36.919+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:16:36.915+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T18:16:36.920+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T18:16:36.933+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.903 seconds
[2024-04-07T18:17:07.132+0000] {processor.py:161} INFO - Started process (PID=3055) to work on /opt/airflow/dags/evidently.py
[2024-04-07T18:17:07.133+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T18:17:07.134+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:17:07.134+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T18:17:09.136+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:17:09.132+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T18:17:09.138+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T18:17:09.151+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 2.021 seconds
[2024-04-07T18:17:39.317+0000] {processor.py:161} INFO - Started process (PID=3103) to work on /opt/airflow/dags/evidently.py
[2024-04-07T18:17:39.318+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/evidently.py for tasks to queue
[2024-04-07T18:17:39.318+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:17:39.318+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/evidently.py
[2024-04-07T18:17:41.152+0000] {logging_mixin.py:188} INFO - [2024-04-07T18:17:41.147+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/evidently.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/evidently.py", line 10, in <module>
    from evidently import ColumnMapping, Report
ImportError: cannot import name 'Report' from 'evidently' (/home/airflow/.local/lib/python3.8/site-packages/evidently/__init__.py)
[2024-04-07T18:17:41.154+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/evidently.py
[2024-04-07T18:17:41.167+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/evidently.py took 1.853 seconds
